/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityItem: typeof import('./components/dashboard/ActivityItem.vue')['default']
    ApiKeys: typeof import('./components/system/ApiKeys.vue')['default']
    ApiOutbox: typeof import('./components/outbox/ApiOutbox.vue')['default']
    BulkOutbox: typeof import('./components/outbox/BulkOutbox.vue')['default']
    BulkTopups: typeof import('./components/topups/BulkTopups.vue')['default']
    CampaignManager: typeof import('./components/campaigns/CampaignManager.vue')['default']
    ContactGroups: typeof import('./components/contacts/ContactGroups.vue')['default']
    ContactManager: typeof import('./components/contacts/ContactManager.vue')['default']
    DashboardStats: typeof import('./components/dashboard/DashboardStats.vue')['default']
    DeliveryChart: typeof import('./components/charts/DeliveryChart.vue')['default']
    MessageManager: typeof import('./components/messages/MessageManager.vue')['default']
    PerformanceChart: typeof import('./components/charts/PerformanceChart.vue')['default']
    PremiumOutbox: typeof import('./components/outbox/PremiumOutbox.vue')['default']
    QuickActionButton: typeof import('./components/dashboard/QuickActionButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Senders: typeof import('./components/senders/Senders.vue')['default']
    SmsInbox: typeof import('./components/outbox/SmsInbox.vue')['default']
    SmsServiceManager: typeof import('./components/sms-services/SmsServiceManager.vue')['default']
    StatCard: typeof import('./components/dashboard/StatCard.vue')['default']
    StopList: typeof import('./components/senders/StopList.vue')['default']
    SystemManager: typeof import('./components/system/SystemManager.vue')['default']
    Transactions: typeof import('./components/transactions/Transactions.vue')['default']
    UsageStats: typeof import('./components/usage/UsageStats.vue')['default']
  }
}
